//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtividadeProfissional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AtividadeProfissional()
        {
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
        }
    
        public int AtividadeProfissionalId { get; set; }
        public int ProfessorId { get; set; }
        public int SequenciaAtividadeProfissional { get; set; }
        public int InstituicaoEmpresaId { get; set; }
        public Nullable<int> UnidadeInstituicaoEmpresaId { get; set; }
        public Nullable<int> OrgaoInstituicaoEmpresaId { get; set; }
        public System.DateTime DataInicioAtividadeProfissional { get; set; }
        public Nullable<System.DateTime> DataTerminoAtividadeProfissional { get; set; }
        public string InformacoesAdicionaisAtividadeProfissional { get; set; }
        public string TipoAtividadeProfissional { get; set; }
    
        public virtual InstituicaoEmpresa InstituicaoEmpresa { get; set; }
        public virtual OrgaoInstituicaoEmpresa OrgaoInstituicaoEmpresa { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual UnidadeInstituicaoEmpresa UnidadeInstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
    }
}
