//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancaDeTrabalho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BancaDeTrabalho()
        {
            this.AreaConhecimento = new HashSet<AreaConhecimento>();
            this.PalavraChave = new HashSet<PalavraChave>();
            this.Professor = new HashSet<Professor>();
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
        }
    
        public int BancaDeTrabalhoId { get; set; }
        public string NaturezaBancaDeTrabalho { get; set; }
        public string TipoBancaDeTrabalho { get; set; }
        public string TituloBancaDeTrabalho { get; set; }
        public decimal AnoBancaDeTrabalho { get; set; }
        public string PaisBancaDeTrabalho { get; set; }
        public Nullable<int> IdiomaId { get; set; }
        public string HomePageBancaDeTrabalho { get; set; }
        public string DOIBancaDeTrabalho { get; set; }
        public string TituloEmInglesBancaDeTrabalho { get; set; }
        public string NomeDoCandidatoBancaDeTrabalho { get; set; }
        public Nullable<int> InstituicaoEmpresaId { get; set; }
        public Nullable<int> CursoId { get; set; }
        public string InformacoesAdicionaisBancaDeTrabalho { get; set; }
        public string InformacoesAdicionaisEmInglesBancaDeTrabalho { get; set; }
        public Nullable<int> OrgaoInstituicaoEmpresaId { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresa { get; set; }
        public virtual OrgaoInstituicaoEmpresa OrgaoInstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaConhecimento> AreaConhecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalavraChave> PalavraChave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor> Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
    }
}
