//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDeConsulta
    {
        public int ProfessorId { get; set; }
        public decimal AnoBaseDeConsulta { get; set; }
        public int SequenciaBaseDeConsulta { get; set; }
        public Nullable<int> InstituicaoEmpresaId { get; set; }
        public Nullable<int> UnidadeInstituicaoEmpresaId { get; set; }
        public Nullable<int> OrgaoInstituicaoEmpresaId { get; set; }
        public Nullable<int> AreaConhecimentoId { get; set; }
        public Nullable<int> PalavraChaveId { get; set; }
        public Nullable<int> IdiomaId { get; set; }
        public Nullable<int> CursoId { get; set; }
        public Nullable<int> ProjetoId { get; set; }
        public Nullable<int> EventoId { get; set; }
        public Nullable<int> AgenciaFinanciadoraId { get; set; }
        public Nullable<int> ProducaoBibliograficaId { get; set; }
        public Nullable<int> ProducaoTecnicaId { get; set; }
        public Nullable<int> BancaDeTrabalhoId { get; set; }
        public Nullable<int> BancaJulgadoraId { get; set; }
        public Nullable<int> AtividadeProfissionalId { get; set; }
        public Nullable<int> ParticipacaoEventoId { get; set; }
        public Nullable<int> FormacaoAcademicaTitulacaoId { get; set; }
        public Nullable<int> OrientacaoSupervisaoId { get; set; }
        public Nullable<int> PremioOuTituloId { get; set; }
        public Nullable<int> VinculoAtuacaoProfissionalId { get; set; }
        public Nullable<int> ParticipacaoEmProjetoId { get; set; }
    
        public virtual AgenciaFinanciadora AgenciaFinanciadora { get; set; }
        public virtual AreaConhecimento AreaConhecimento { get; set; }
        public virtual AtividadeProfissional AtividadeProfissional { get; set; }
        public virtual BancaDeTrabalho BancaDeTrabalho { get; set; }
        public virtual BancaJulgadora BancaJulgadora { get; set; }
        public virtual BaseDeConsulta BaseDeConsulta1 { get; set; }
        public virtual BaseDeConsulta BaseDeConsulta2 { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual FormacaoAcademicaTitulacao FormacaoAcademicaTitulacao { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresa { get; set; }
        public virtual OrgaoInstituicaoEmpresa OrgaoInstituicaoEmpresa { get; set; }
        public virtual OrientacaoSupervisao OrientacaoSupervisao { get; set; }
        public virtual PalavraChave PalavraChave { get; set; }
        public virtual ParticipacaoEmProjeto ParticipacaoEmProjeto { get; set; }
        public virtual ParticipacaoEvento ParticipacaoEvento { get; set; }
        public virtual PremioOuTitulo PremioOuTitulo { get; set; }
        public virtual ProducaoBibliografica ProducaoBibliografica { get; set; }
        public virtual ProducaoTecnica ProducaoTecnica { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual UnidadeInstituicaoEmpresa UnidadeInstituicaoEmpresa { get; set; }
        public virtual VinculoAtuacaoProfissional VinculoAtuacaoProfissional { get; set; }
        public virtual Projeto Projeto { get; set; }
    }
}
