//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContatoProfessor
    {
        public int ProfessorId { get; set; }
        public string TipoContato { get; set; }
        public string TelefoneContato { get; set; }
        public string RamalContato { get; set; }
        public string FaxContato { get; set; }
        public string EMailContato { get; set; }
        public string SiteContato { get; set; }
        public string CaixaPostalContato { get; set; }
    
        public virtual Professor Professor { get; set; }
    }
}
