//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.BancaDeTrabalho = new HashSet<BancaDeTrabalho>();
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
            this.FormacaoAcademicaTitulacao = new HashSet<FormacaoAcademicaTitulacao>();
            this.OrientacaoSupervisao = new HashSet<OrientacaoSupervisao>();
        }
    
        public int InstituicaoEmpresaId { get; set; }
        public int CursoId { get; set; }
        public string NomeCurso { get; set; }
        public string TipoFormacaoCurso { get; set; }
        public string CodigoCapesCurso { get; set; }
        public string NomeCursoEmIngles { get; set; }
        public string GrandeAreaConhecimento { get; set; }
        public string AreaConhecimento { get; set; }
        public string SubAreaConhecimento { get; set; }
        public string Especialidade { get; set; }
        public string TermoCompleto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancaDeTrabalho> BancaDeTrabalho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrientacaoSupervisao> OrientacaoSupervisao { get; set; }
    }
}
