//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
            this.ParticipacaoEvento = new HashSet<ParticipacaoEvento>();
        }
    
        public int EventoId { get; set; }
        public decimal AnoEvento { get; set; }
        public string PaisEvento { get; set; }
        public string NomeEvento { get; set; }
        public Nullable<int> InstituicaoEmpresaId { get; set; }
        public string CidadeEvento { get; set; }
        public string NaturezaEvento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipacaoEvento> ParticipacaoEvento { get; set; }
    }
}
