//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtratoQualis
    {
        public string AreaAvaliacaoPeriodicoQualis { get; set; }
        public string ExtratoPeriodicoQualis { get; set; }
        public int PeriodicoQualisId { get; set; }
    
        public virtual PeriodicoQualis PeriodicoQualis { get; set; }
    }
}
