//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormacaoAcademicaTitulacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormacaoAcademicaTitulacao()
        {
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
            this.AreaConhecimento = new HashSet<AreaConhecimento>();
            this.PalavraChave = new HashSet<PalavraChave>();
        }
    
        public int FormacaoAcademicaTitulacaoId { get; set; }
        public int ProfessorId { get; set; }
        public int SequenciaFormacaoAcademicaTitulacao { get; set; }
        public string NivelFormacaoAcademicaTitulacao { get; set; }
        public string TituloTrabalhoFinal { get; set; }
        public string TituloTrabalhoFinalEmIngles { get; set; }
        public Nullable<int> OrientadorId { get; set; }
        public int InstituicaoEmpresaId { get; set; }
        public Nullable<int> CursoId { get; set; }
        public string CodigoAreaCurso { get; set; }
        public string SituacaoFormacaoAcademicaTitulacao { get; set; }
        public decimal AnoInicioFormacaoAcademicaTitulacao { get; set; }
        public Nullable<decimal> AnoConclusaoFormacaoAcademicaTitulacao { get; set; }
        public Nullable<bool> TemBolsaFormacaoAcademicaTitulacao { get; set; }
        public Nullable<int> AgenciaFinanciadoraId { get; set; }
        public string TipoGraduacaoDoutorado { get; set; }
        public Nullable<decimal> CargaHorariaFormacaoAcademicaTitulacao { get; set; }
        public Nullable<decimal> AnoObtencaoTituloFormacaoAcademicaTitulacao { get; set; }
        public Nullable<int> OrientadorCoTutelaId { get; set; }
        public Nullable<int> InstituicaoEmpresaCoTutelaId { get; set; }
        public Nullable<int> OrientadorSanduicheId { get; set; }
        public Nullable<int> InstituicaoEmpresaSanduicheId { get; set; }
        public Nullable<int> InstituicaoEmpresaOutraSanduicheId { get; set; }
        public Nullable<int> OrgaoInstituicaoEmpresaId { get; set; }
        public Nullable<int> CoOrientadorId { get; set; }
    
        public virtual AgenciaFinanciadora AgenciaFinanciadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Orientador CoOrientador { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresa { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresaCoTutela { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresaOutraSanduiche { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresaSanduiche { get; set; }
        public virtual OrgaoInstituicaoEmpresa OrgaoInstituicaoEmpresa { get; set; }
        public virtual Orientador Orientador { get; set; }
        public virtual Orientador OrientadorCoTutela { get; set; }
        public virtual Orientador OrientadorSanduiche { get; set; }
        public virtual Professor Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaConhecimento> AreaConhecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalavraChave> PalavraChave { get; set; }
    }
}
