//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdiomasProfessor
    {
        public int ProfessorId { get; set; }
        public int IdiomaId { get; set; }
        public string ProeficienciaLeituraProfessor { get; set; }
        public string ProeficienciaFalaProfessor { get; set; }
        public string ProeficienciaEscritaProfessor { get; set; }
        public string ProeficienciaCompreensaoProfessor { get; set; }
        public string NomeIdioma { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
