//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstituicaoEmpresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstituicaoEmpresa()
        {
            this.AtividadeProfissional = new HashSet<AtividadeProfissional>();
            this.BancaDeTrabalho = new HashSet<BancaDeTrabalho>();
            this.BancaJulgadora = new HashSet<BancaJulgadora>();
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
            this.Curso = new HashSet<Curso>();
            this.Evento = new HashSet<Evento>();
            this.FormacaoAcademicaTitulacao = new HashSet<FormacaoAcademicaTitulacao>();
            this.FormacaoAcademicaTitulacao1 = new HashSet<FormacaoAcademicaTitulacao>();
            this.FormacaoAcademicaTitulacao2 = new HashSet<FormacaoAcademicaTitulacao>();
            this.FormacaoAcademicaTitulacao3 = new HashSet<FormacaoAcademicaTitulacao>();
            this.VinculoAtuacaoProfissional = new HashSet<VinculoAtuacaoProfissional>();
            this.OrgaoInstituicaoEmpresa = new HashSet<OrgaoInstituicaoEmpresa>();
            this.OrientacaoSupervisao = new HashSet<OrientacaoSupervisao>();
            this.Professor = new HashSet<Professor>();
            this.Projeto = new HashSet<Projeto>();
            this.UnidadeInstituicaoEmpresa = new HashSet<UnidadeInstituicaoEmpresa>();
            this.Projeto1 = new HashSet<Projeto>();
        }
    
        public int InstituicaoEmpresaId { get; set; }
        public string NomeInstituicaoEmpresa { get; set; }
        public string SiglaInstituicaoEmpresa { get; set; }
        public Nullable<bool> EnsinoInstituicaoEmpresa { get; set; }
        public string PaisInstituicaoEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtividadeProfissional> AtividadeProfissional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancaDeTrabalho> BancaDeTrabalho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancaJulgadora> BancaJulgadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curso> Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento> Evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VinculoAtuacaoProfissional> VinculoAtuacaoProfissional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgaoInstituicaoEmpresa> OrgaoInstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrientacaoSupervisao> OrientacaoSupervisao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor> Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projeto> Projeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnidadeInstituicaoEmpresa> UnidadeInstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projeto> Projeto1 { get; set; }
    }
}
