//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JCR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JCR()
        {
            this.ProducaoBibliografica = new HashSet<ProducaoBibliografica>();
        }
    
        public int JCRId { get; set; }
        public int Rank { get; set; }
        public string NomePeriodicoJCR { get; set; }
        public string NomeAbreviadoPeriodioJCR { get; set; }
        public string ISSNJCR { get; set; }
        public Nullable<int> NumeroCitacoesJCR { get; set; }
        public Nullable<decimal> FatorImpactoJCR { get; set; }
        public Nullable<decimal> FatorImpactoSemCitacoesPropriasJCR { get; set; }
        public Nullable<decimal> FatorImpactoCincoAnosJCR { get; set; }
        public Nullable<decimal> IndiceInfluenciaJCR { get; set; }
        public Nullable<int> ItensCitaveisJCR { get; set; }
        public Nullable<decimal> PontuacaoEigenfactorJCR { get; set; }
        public Nullable<decimal> PontuacaoInfluenciaArtigoJCR { get; set; }
        public Nullable<decimal> PercentualMedioJCR { get; set; }
        public Nullable<decimal> EigenfactorNormalizadoJCR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProducaoBibliografica> ProducaoBibliografica { get; set; }
    }
}
