//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrientacaoSupervisao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrientacaoSupervisao()
        {
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
            this.AreaConhecimento = new HashSet<AreaConhecimento>();
            this.PalavraChave = new HashSet<PalavraChave>();
        }
    
        public int OrientacaoSupervisaoId { get; set; }
        public int ProfessorId { get; set; }
        public int SequenciaOrientacaoSupervicao { get; set; }
        public string TipoOrientacaoSupervicao { get; set; }
        public string NaturezaOrientacaoSupervicao { get; set; }
        public string TituloOrientacaoSupervicao { get; set; }
        public decimal AnoOrientacaoSupervicao { get; set; }
        public string PaisOrientacaoSupervicao { get; set; }
        public Nullable<int> IdiomaId { get; set; }
        public string HomePageOrientacaoSupervicao { get; set; }
        public string DOIOrientacaoSupervicao { get; set; }
        public string TituloEmInglesOrientacaoSupervicao { get; set; }
        public string NomeOrientandoOrientacaoSupervicao { get; set; }
        public Nullable<int> InstituicaoEmpresaId { get; set; }
        public Nullable<bool> TemBolsaOrientacaoSupervicao { get; set; }
        public Nullable<int> AgenciaFinanciadoraId { get; set; }
        public string PapelOrientacaoSupervicao { get; set; }
        public string InformacoesAdicionaisOrientacaoSupervicao { get; set; }
        public string InformacoesAdicionaisEmInglesOrientacaoSupervicao { get; set; }
        public Nullable<int> CursoId { get; set; }
        public Nullable<int> OrgaoInstituicaoEmpresaId { get; set; }
    
        public virtual AgenciaFinanciadora AgenciaFinanciadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresa { get; set; }
        public virtual OrgaoInstituicaoEmpresa OrgaoInstituicaoEmpresa { get; set; }
        public virtual Professor Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaConhecimento> AreaConhecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalavraChave> PalavraChave { get; set; }
    }
}
