//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orientador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orientador()
        {
            this.FormacaoAcademicaTitulacao = new HashSet<FormacaoAcademicaTitulacao>();
            this.FormacaoAcademicaTitulacao1 = new HashSet<FormacaoAcademicaTitulacao>();
            this.FormacaoAcademicaTitulacao2 = new HashSet<FormacaoAcademicaTitulacao>();
            this.FormacaoAcademicaTitulacao3 = new HashSet<FormacaoAcademicaTitulacao>();
        }
    
        public int OrientadorId { get; set; }
        public string NomeOrientador { get; set; }
        public string NumeroCurriculoOrientador { get; set; }
        public Nullable<int> ProfessorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao3 { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
