//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipacaoEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipacaoEvento()
        {
            this.AreaConhecimento = new HashSet<AreaConhecimento>();
            this.PalavraChave = new HashSet<PalavraChave>();
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
        }
    
        public int ProfessorId { get; set; }
        public int EventoId { get; set; }
        public string TipoParticipacaoEvento { get; set; }
        public string FormaParticipacaoEvento { get; set; }
        public Nullable<int> IdiomaId { get; set; }
        public string TituloParticipacaoEvento { get; set; }
        public string TituloEmInglesParticipacaoEvento { get; set; }
        public string InformacoesAdicionaisParticipacaoEvento { get; set; }
        public string InformacoesAdicionaisEmInglesParticipacaoEvento { get; set; }
        public string MeioDivulgacaoParticipacaoEvento { get; set; }
        public string HomePageParticipacaoEvento { get; set; }
        public string DOIParticipacaoEvento { get; set; }
        public Nullable<bool> DivulgacaoCeTParticipacaoEvento { get; set; }
        public int SequenciaParticipacaoEvento { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual Professor Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaConhecimento> AreaConhecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalavraChave> PalavraChave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
    }
}
