//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatenteRegistro
    {
        public int ProducaoTecnicaId { get; set; }
        public int SequenciaPatenteRegistro { get; set; }
        public string TipoPatenteRegistro { get; set; }
        public string CodigoPatenteRegistro { get; set; }
        public string TituloPatenteRegistro { get; set; }
        public Nullable<System.DateTime> DataPedidoPatenteRegistro { get; set; }
        public Nullable<System.DateTime> DataPedidoExamePatenteRegistro { get; set; }
        public Nullable<System.DateTime> DataConcessaoPatenteRegistro { get; set; }
        public string NumeroDepositoPCTPatenteRegistro { get; set; }
        public Nullable<System.DateTime> DataDepositoPCTPatenteRegistro { get; set; }
        public string NomeTitularPatenteRegistro { get; set; }
        public string InstituicaoDepositoPatenteRegistro { get; set; }
    
        public virtual ProducaoTecnica ProducaoTecnica { get; set; }
    }
}
