//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremioOuTitulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PremioOuTitulo()
        {
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
        }
    
        public int PremioOuTituloId { get; set; }
        public int ProfessorId { get; set; }
        public int SequenciaPremioOuTitulo { get; set; }
        public string NomePremioOuTitulo { get; set; }
        public string EntidadePromotoraPremioOuTitulo { get; set; }
        public decimal AnoPremioOuTitulo { get; set; }
        public string NomePremioOuTituloEmIngles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
