//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducaoBibliografica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProducaoBibliografica()
        {
            this.Professor = new HashSet<Professor>();
            this.PalavraChave = new HashSet<PalavraChave>();
            this.AreaConhecimento = new HashSet<AreaConhecimento>();
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
        }
    
        public int ProducaoBibliograficaId { get; set; }
        public string NaturezaProducaoBibligrafica { get; set; }
        public string TipoProducaoBibligrafica { get; set; }
        public string TituloProducaoBibligrafica { get; set; }
        public decimal AnoProducaoBibligrafica { get; set; }
        public string PaisProducaoBibligrafica { get; set; }
        public Nullable<int> IdiomaId { get; set; }
        public string MeioDivulgacaoProducaoBibligrafica { get; set; }
        public string HomePageProducaoBibligrafica { get; set; }
        public string DOIProducaoBibligrafica { get; set; }
        public string ISBNProducaoBibligrafica { get; set; }
        public string InformacoesAdicionaisProducaoBibligrafica { get; set; }
        public bool DivulgacaoCeTProducaoBibligrafica { get; set; }
        public string InformacoesAdicionaisEmInglesProducaoBibligrafica { get; set; }
        public string TituloEmInglesProducaoBibligrafica { get; set; }
        public Nullable<int> PeriodicoQualisId { get; set; }
        public Nullable<int> JCRId { get; set; }
        public string NomePeriodicoProducaoBibliografica { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor> Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalavraChave> PalavraChave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaConhecimento> AreaConhecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
        public virtual PeriodicoQualis PeriodicoQualis { get; set; }
        public virtual JCR JCR { get; set; }
    }
}
