//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducaoTecnica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProducaoTecnica()
        {
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
            this.PatenteRegistro = new HashSet<PatenteRegistro>();
            this.Professor = new HashSet<Professor>();
            this.AreaConhecimento = new HashSet<AreaConhecimento>();
            this.PalavraChave = new HashSet<PalavraChave>();
        }
    
        public int ProducaoTecnicaId { get; set; }
        public string TituloProducaoTecnica { get; set; }
        public string TipoProducaoTecnica { get; set; }
        public decimal AnoProducaoTecnica { get; set; }
        public string PaisProducaoTecnica { get; set; }
        public Nullable<int> IdiomaId { get; set; }
        public string MeioDivulgacaoProducaoTecnica { get; set; }
        public string HomePageProducaoTecnica { get; set; }
        public string DOIProducaoTecnica { get; set; }
        public Nullable<bool> DivulgacaoCeTProducaoTecnica { get; set; }
        public Nullable<bool> PotencialInovacaoProducaoTecnica { get; set; }
        public string InformacoesAdicionaisProducaoTecnica { get; set; }
        public Nullable<bool> PatentiadoOuRegistradoProducaoTecnica { get; set; }
        public string NaturezaProducaoTecnica { get; set; }
        public Nullable<int> AgenciaFinanciadoraId { get; set; }
        public string InformacoesAdicionaisEmInglesProducaoTecnica { get; set; }
        public string TituloEmInglesProducaoTecnica { get; set; }
    
        public virtual AgenciaFinanciadora AgenciaFinanciadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
        public virtual Idioma Idioma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatenteRegistro> PatenteRegistro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor> Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaConhecimento> AreaConhecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalavraChave> PalavraChave { get; set; }
    }
}
