//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professor()
        {
            this.AreaAtuacao = new HashSet<AreaAtuacao>();
            this.AtividadeProfissional = new HashSet<AtividadeProfissional>();
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
            this.ContatoProfessor = new HashSet<ContatoProfessor>();
            this.FormacaoAcademicaTitulacao = new HashSet<FormacaoAcademicaTitulacao>();
            this.IdiomasProfessor = new HashSet<IdiomasProfessor>();
            this.LinhaDePesquisa = new HashSet<LinhaDePesquisa>();
            this.OrientacaoSupervisao = new HashSet<OrientacaoSupervisao>();
            this.Orientador = new HashSet<Orientador>();
            this.ParticipacaoEmProjeto = new HashSet<ParticipacaoEmProjeto>();
            this.ParticipacaoEvento = new HashSet<ParticipacaoEvento>();
            this.PremioOuTitulo = new HashSet<PremioOuTitulo>();
            this.VinculoAtuacaoProfissional = new HashSet<VinculoAtuacaoProfissional>();
            this.ProducaoBibliografica = new HashSet<ProducaoBibliografica>();
            this.ProducaoTecnica = new HashSet<ProducaoTecnica>();
            this.BancaDeTrabalho = new HashSet<BancaDeTrabalho>();
            this.BancaJulgadora = new HashSet<BancaJulgadora>();
        }
    
        public int ProfessorId { get; set; }
        public string NumeroCurriculo { get; set; }
        public string NomeProfessor { get; set; }
        public string NomeEmCitacoesProfessor { get; set; }
        public Nullable<int> EnderecoResidencialId { get; set; }
        public string LogradouroResidencial { get; set; }
        public Nullable<int> EnderecoProfissionalId { get; set; }
        public string LogradouroProfissional { get; set; }
        public Nullable<int> InstituicaoEmpresaId { get; set; }
        public System.DateTime DataUltimaAtualizacaoCurriculo { get; set; }
        public System.DateTime DataUltimaPublicacaoCurriculo { get; set; }
        public string LinkParaCurriculo { get; set; }
        public Nullable<int> UnidadeInstituicaoEmpresaId { get; set; }
        public Nullable<int> OrgaoInstituicaoEmpresaId { get; set; }
        public string NacionalidadeProfessor { get; set; }
        public string PaisNascimentoProfessor { get; set; }
        public string UFNascimentoProfessor { get; set; }
        public string CidadeNascimentoProfessor { get; set; }
        public string PaisNascionalidadeProfessor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaAtuacao> AreaAtuacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtividadeProfissional> AtividadeProfissional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContatoProfessor> ContatoProfessor { get; set; }
        public virtual Endereco EnderecoProfissional { get; set; }
        public virtual Endereco EnderecoResidencial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormacaoAcademicaTitulacao> FormacaoAcademicaTitulacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdiomasProfessor> IdiomasProfessor { get; set; }
        public virtual InstituicaoEmpresa InstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinhaDePesquisa> LinhaDePesquisa { get; set; }
        public virtual OrgaoInstituicaoEmpresa OrgaoInstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrientacaoSupervisao> OrientacaoSupervisao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orientador> Orientador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipacaoEmProjeto> ParticipacaoEmProjeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipacaoEvento> ParticipacaoEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PremioOuTitulo> PremioOuTitulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VinculoAtuacaoProfissional> VinculoAtuacaoProfissional { get; set; }
        public virtual UnidadeInstituicaoEmpresa UnidadeInstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProducaoBibliografica> ProducaoBibliografica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProducaoTecnica> ProducaoTecnica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancaDeTrabalho> BancaDeTrabalho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancaJulgadora> BancaJulgadora { get; set; }
    }
}
