//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.Entities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projeto()
        {
            this.ParticipacaoEmProjeto = new HashSet<ParticipacaoEmProjeto>();
            this.InstituicaoEmpresaFinanciadora = new HashSet<InstituicaoEmpresa>();
            this.BaseDeConsulta = new HashSet<BaseDeConsulta>();
        }
    
        public int ProjetoId { get; set; }
        public int InstituicaoEmpresaId { get; set; }
        public decimal AnoInicioProjeto { get; set; }
        public Nullable<decimal> AnoFimProjeto { get; set; }
        public string NomeProjeto { get; set; }
        public string SituacaoProjeto { get; set; }
        public string NaturezaProjeto { get; set; }
        public Nullable<bool> PotencialInovacao { get; set; }
        public int OrgaoInstituicaoEmpresaId { get; set; }
        public int UnidadeInstituicaoEmpresaId { get; set; }
        public string InformacoesAdicionaisProjeto { get; set; }
        public string InformacoesAdicionaisEmInglesProjeto { get; set; }
        public string NomeEmInglesProjeto { get; set; }
    
        public virtual InstituicaoEmpresa InstituicaoEmpresa { get; set; }
        public virtual OrgaoInstituicaoEmpresa OrgaoInstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipacaoEmProjeto> ParticipacaoEmProjeto { get; set; }
        public virtual UnidadeInstituicaoEmpresa UnidadeInstituicaoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstituicaoEmpresa> InstituicaoEmpresaFinanciadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeConsulta> BaseDeConsulta { get; set; }
    }
}
