//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by v tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LattesExtractor.CurriculoLattesWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.servico.repositorio.cnpq.br/", ConfigurationName="CurriculoLattesWebService.WSCurriculo")]
    public interface WSCurriculo {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        byte[] getCurriculoCompactado(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<byte[]> getCurriculoCompactadoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        byte[] getCurriculoCompactadoPorUsuario(string id, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<byte[]> getCurriculoCompactadoPorUsuarioAsync(string id, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getDataAtualizacaoCV(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getDataAtualizacaoCVAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getDataAtualizacaoCVPorUsuario(string id, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getDataAtualizacaoCVPorUsuarioAsync(string id, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getIdentificadorCNPq(string cpf, string nomeCompleto, string dataNascimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getIdentificadorCNPqAsync(string cpf, string nomeCompleto, string dataNascimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getIdentificadorCNPqPorUsuario(string cpf, string nomeCompleto, string dataNascimento, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getIdentificadorCNPqPorUsuarioAsync(string cpf, string nomeCompleto, string dataNascimento, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getOcorrenciaCV(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOcorrenciaCVAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getOcorrenciaCVPorUsuario(string id, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOcorrenciaCVPorUsuarioAsync(string id, string login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCurriculoChannel : LattesExtractor.CurriculoLattesWebService.WSCurriculo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCurriculoClient : System.ServiceModel.ClientBase<LattesExtractor.CurriculoLattesWebService.WSCurriculo>, LattesExtractor.CurriculoLattesWebService.WSCurriculo {
        
        public WSCurriculoClient() {
        }
        
        public WSCurriculoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCurriculoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCurriculoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCurriculoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] getCurriculoCompactado(string id) {
            return base.Channel.getCurriculoCompactado(id);
        }
        
        public System.Threading.Tasks.Task<byte[]> getCurriculoCompactadoAsync(string id) {
            return base.Channel.getCurriculoCompactadoAsync(id);
        }
        
        public byte[] getCurriculoCompactadoPorUsuario(string id, string login) {
            return base.Channel.getCurriculoCompactadoPorUsuario(id, login);
        }
        
        public System.Threading.Tasks.Task<byte[]> getCurriculoCompactadoPorUsuarioAsync(string id, string login) {
            return base.Channel.getCurriculoCompactadoPorUsuarioAsync(id, login);
        }
        
        public string getDataAtualizacaoCV(string id) {
            return base.Channel.getDataAtualizacaoCV(id);
        }
        
        public System.Threading.Tasks.Task<string> getDataAtualizacaoCVAsync(string id) {
            return base.Channel.getDataAtualizacaoCVAsync(id);
        }
        
        public string getDataAtualizacaoCVPorUsuario(string id, string login) {
            return base.Channel.getDataAtualizacaoCVPorUsuario(id, login);
        }
        
        public System.Threading.Tasks.Task<string> getDataAtualizacaoCVPorUsuarioAsync(string id, string login) {
            return base.Channel.getDataAtualizacaoCVPorUsuarioAsync(id, login);
        }
        
        public string getIdentificadorCNPq(string cpf, string nomeCompleto, string dataNascimento) {
            return base.Channel.getIdentificadorCNPq(cpf, nomeCompleto, dataNascimento);
        }
        
        public System.Threading.Tasks.Task<string> getIdentificadorCNPqAsync(string cpf, string nomeCompleto, string dataNascimento) {
            return base.Channel.getIdentificadorCNPqAsync(cpf, nomeCompleto, dataNascimento);
        }
        
        public string getIdentificadorCNPqPorUsuario(string cpf, string nomeCompleto, string dataNascimento, string login) {
            return base.Channel.getIdentificadorCNPqPorUsuario(cpf, nomeCompleto, dataNascimento, login);
        }
        
        public System.Threading.Tasks.Task<string> getIdentificadorCNPqPorUsuarioAsync(string cpf, string nomeCompleto, string dataNascimento, string login) {
            return base.Channel.getIdentificadorCNPqPorUsuarioAsync(cpf, nomeCompleto, dataNascimento, login);
        }
        
        public string getOcorrenciaCV(string id) {
            return base.Channel.getOcorrenciaCV(id);
        }
        
        public System.Threading.Tasks.Task<string> getOcorrenciaCVAsync(string id) {
            return base.Channel.getOcorrenciaCVAsync(id);
        }
        
        public string getOcorrenciaCVPorUsuario(string id, string login) {
            return base.Channel.getOcorrenciaCVPorUsuario(id, login);
        }
        
        public System.Threading.Tasks.Task<string> getOcorrenciaCVPorUsuarioAsync(string id, string login) {
            return base.Channel.getOcorrenciaCVPorUsuarioAsync(id, login);
        }
    }
}
